import { PartnerRetailer, PartnerWholesaler } from "@/types/PartnersType";

export const wholesalerList: PartnerWholesaler[] = [
  {
    id: "w1",
    businessName: "Bajrang Lal Manoj Kumar",
    city: "Patna",
    zone: "North",
    phone: "7633996701",
    category: "",
    emailID: "bajranglalmanojkumar@gmail.com",
    proprietor: "",
    address:
      "2nd Floor, Vision Rupak Commercial Complex, Rupak Cinema Campus, Bakarhanj, 800004",
  },
  {
    id: "w2",
    businessName: "Mungipa Texttile",
    city: "Patna",
    zone: "North",
    phone: "9430032448",
    category: "",
    emailID: "mungipa.textile@gmail.com",
    proprietor: "",
    address:
      "Shop No-104-109, 6th floor, Khetan Super Market, Birla Mandir Road, 800004",
  },
  {
    id: "w3",
    businessName: "Gaurav Synthetics",
    city: "Patna",
    zone: "South",
    phone: "9431017037",
    category: "",
    emailID: "gauravsynthetic@gmail.com",
    proprietor: "",
    address:
      "3nd Floor, Hari Sabha Commercial Complex, Sabjibagh, Near Ashok Rajpath, 800004",
  },
  {
    id: "w4",
    businessName: "Panna Lal Om Prakash",
    city: "Patna",
    zone: "North",
    phone: "9693222759",
    category: "",
    emailID: "pannalalomprakash.patna@gmail.com",
    proprietor: "",
    address:
      "F/1-4, Khetan Super Market Birla Mandir Road, Patna",
  },
  {
    id: "w5",
    businessName: "Rampuria Vanijya",
    city: "Kolkata",
    zone: "East",
    phone: "9693222759",
    category: "",
    emailID: "rampuriajay@yahoo.co.in",
    proprietor: "",
    address:
      "107, Old China Bazar Street, 2nd Floor (Ram Rahim Market), Brabourne Road, Kolkata - 700001",
  },
  {
    id: "w6",
    businessName: "Vineet Fashions",
    city: "Delhi",
    zone: "West",
    phone: "011-49072061",
    category: "",
    emailID: "vineetfashions1@gmail.com",
    proprietor: "",
    address: "771, Gali Tellaiya, Katra Neel, Chandani Chowk, Delhi - 110006"
  },
  {
    id: "w7",
    businessName: "PGI Distributors PVT. LTD.",
    city: "Kolkata",
    zone: "South",
    phone: "011-49072061",
    category: "",
    emailID: "pgidistributors@primarc.in",
    proprietor: "",
    address: "3, Synagogue Street, Kolkata - 700001"
  },
  {
    id: "w8",
    businessName: "Gaurav Creation",
    city: "Bihar",
    zone: "North",
    phone: "9377817976",
    category: "",
    emailID: "gauravc@gmail.in",
    proprietor: "",
    address: "Bhagwandas Baijnath Rajgarhia Chowk, Munger, Bihar - 811201"
  },
];

export const retailerList: PartnerRetailer[] = [
  {
    id: "rt1",
    businessName: "Daisy Enterprises",
    address: "#215, Celebrity Community, Sarjapur-Attibele, Bnagalore- 562107",
    zone: "South",
    category: "",
    city: "Bangalore",
    emailID: "daisy.shivanshi@gmail.com",
    phone: "7008978123",
    proprietor: "",
    reference: "",
  },
  {
    id: "rt2",
    businessName: "RR Enterprises",
    address: "Shop No-104-109, 6th floor, Khetan Super Market, Birla Mandir Road, 800004",
    zone: "North",
    category: "",
    city: "Patna",
    emailID: "rrRushil@gmail.com",
    phone: "9430032448",
    proprietor: "",
    reference: "",
  },
  {
    id: "rt3",
    businessName: "Dhinesh Rajgarhia",
    address: "Flat 2, Block D, Prerna Apartments, Gandhi Road, Gwalior - 474001",
    zone: "North",
    category: "",
    city: "Gwalior",
    emailID: "dhinesh002@gmail.com",
    phone: "9912268231",
    proprietor: "",
    reference: "",
  },
  {
    id: "rt4",
    businessName: "Anil Mahajan",
    address: "#24, Bengali Colony, Ramadevi Chowraha, Kanpur - 208007",
    zone: "North",
    category: "",
    city: "Kanpur",
    emailID: "m.anil.awesome@gmail.com",
    phone: "9916645232",
    proprietor: "",
    reference: "",
  },
];
